# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: ghcr.io/criteo-forks/scheduler-plugins/kube-scheduler:v20251215-v0.33.5-criteo1
  command:
  - /bin/kube-scheduler
  replicaCount: 1
  leaderElect: false
  priorityClassName: ""
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []

controller:
  enabled: false
  name: scheduler-plugins-controller
  image: ghcr.io/criteo-forks/scheduler-plugins/controller:v20251215-v0.33.5-criteo1
  replicaCount: 1
  leaderElect: false
  priorityClassName: ""
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: true
  multiPoint:
    enabled: []
    disabled: []
  score:
    enabled:
    - name: NodeMetadata
      weight: 5  # Adjust weight to balance with other scoring plugins


# Customize the enabled plugins' config.
# Refer to the "pluginConfig" section of manifests/<plugin>/scheduler-config.yaml.
# For example, for Coscheduling plugin, you want to customize the permit waiting timeout to 10 seconds:
pluginConfig:
- name: NodeMetadata

  args:
    kind: NodeMetadataArgs
    apiVersion: kubescheduler.config.k8s.io/v1
    metadataKey: "node.example.com/last-maintenance"
    metadataSource: "Annotation"
    metadataType: "Timestamp"
    scoringStrategy: "Newest"
    timestampFormat: "2006-01-02T15:04:05Z07:00"
